server:
  port: 8080
  servlet:
    context-path: /product
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: scott
    password: password
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.product.entity